{% set name = "libcsm" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/csm

build:
  number: 2
  features:
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - vc 14  # [win and (py35 or py36)]
  run:
    - vc  # [win and (py35 or py36)]

test:
  commands:
    - test -e $PREFIX/lib/libcsmapi.so  # [linux]
    - test -e $PREFIX/lib/libcsmapi.dylib  # [osx]
    - test -e $PREFIX/include/csm/Isd.h  # [not win]
    - test -e $PREFIX/include/csm/csm.h  # [not win]
    - if not exist %LIBRARY_BIN%\csmapi.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\csmapi.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\csm\Ellipsoid.h exit 1 # [win]

about:
  home: https://github.com/USGS-Astrogeology/csm
  license: None
  summary: "This is the Community Sensor Model base interface library."

extra:
  recipe-maintainers:
    - jlaura
